<?php
$this->cycle()->assign(array('#F0F0F0', '#FFF'), 'colors');
$this->cycle()->assign(array(1, 2, 3), 'numbers');
?>
<table>
	<?php foreach($books as $book): ?>
				<tr style="background-color: <?php echo $this->cycle()->setName('colors')->next(); ?>">
					<td><?php echo $this->cycle()->setName('numbers')->next(); ?></td>
					<td><?php echo $book; ?></td>
				</tr>
	<?php endforeach; ?>
</table>