<?php

/*$this->headMeta()->appendName('teste', 'zend framework 2');

$this->headMeta()->appendHttpEquiv('expires', 'web, 26 Feb 1997 08:21:57 GMT')
				 ->appendHttpEquiv('progma', 'no-cache')
				 ->appendHttpEquiv('Cache-Control', 'no-cache');*/

/*$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
				 ->appendHttpEquiv('Content-Language', 'en-US');*/

// $this->headMeta()->setCharset('UTF-8');

$this->headMeta()->appendHttpEquiv('Refresh', '3;URL=http://www.some.org/some.html');

echo $this->headMeta();