<?php

$title = 'Meu album';
$this->headTitle($title);
?>

<h6><?php echo $this->escapeHtml($title); ?></h6>
<p>
	<a href="<?php echo $this->url('album', array('action' => 'add')); ?>">Novo Album</a>
</p>
<table class="table">
	<tr>
		<th>Title</th>
		<th>Artist</th>
		<th>&nbsp;</th>
	</tr>
	<?php foreach($this->paginator as $album): ?>
			<tr>
				<td><?php echo $this->escapeHtml($album->title); ?></td>
				<td><?php echo $this->escapeHtml($album->artist); ?></td>
				<td>
					<a href="<?php echo $this->url('album', array('action' => 'edit', 'id' => $album->id)); ?>">Editar</a>
					<a href="<?php echo $this->url('album', array('action' => 'delete', 'id' => $album->id)); ?>">Excluir</a>
				</td>
			</tr>
	<?php endforeach; ?>
</table>

<?php 
	echo $this->paginationControl(
		//o objeto paginador
		$this->paginator,
		//o estilo de rolagem
		'sliding',
		//o parcial de usar para processar o controle
		array('partial/paginator.phtml', 'Album'),
		//a rota de ligação para quando um usuário clica em um link de controle
		array('route' => 'album')
	);
?>